# Generated by Django 3.2.1 on 2021-05-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210507_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='rest_time',
            new_name='rest_time_in_seconds',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='weight',
            new_name='weight_in_pounds',
        ),
    ]
