# Generated by Django 3.2.1 on 2021-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210507_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='rest_time_in_seconds',
            new_name='rest_time_between_sets_in_seconds',
        ),
    ]
