# Generated by Django 3.2.1 on 2021-05-08 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_rest_time_in_seconds_exercise_rest_time_between_sets_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 3, 11, 31, 45436, tzinfo=utc), verbose_name='date created'),
        ),
    ]
